global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flex-academy-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:3001']
        labels:
          app: 'flex-academy'
          env: 'production'
